apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:
    app: nginx
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
  # these are used to select the pod to create replicas
    matchLabels:
      tier: frontend
      app: nginx
  # this is pod defination
  template:
    metadata:
  # this lables belongs to pod 
      labels:
        tier: frontend
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:stable-perl

