kind: Pod
apiVersion: v1
metadata:
  name: labels
  labels:
    project: expense
    module: backend
    environment: dev
sepc:
  containers:
  - name: nginx
    image: nginx
---
kind: Service
apiVersion: v1
metadata: 
  name: nginx
spec:
  selector: 
    project: expense
    module: backend
    environment: dev
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 80
    targetPort: 80